name: CD

on:
  workflow_run:
    workflows: ["CI with Gradle"] # CI 워크플로우 이름과 정확히 일치해야 함
    types: [completed]
    branches: [main] # main 브랜치에서 CI가 성공적으로 끝났을 때만 실행

permissions:
  contents: read

env:
  IMAGE: ${{ secrets.DOCKER_USERNAME }}/bearchive # CI와 동일한 이미지명 사용

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    # CI 워크플로우가 실패하면 실행되지 않도록 조건 추가
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # SSH로 서버에 접속해 배포
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            echo "${{ secrets.ENV_FILE }}" > /home/${{ secrets.SERVER_USER }}/.env
            echo "[1/3] Pull latest Docker image..."
            docker pull ${{ env.IMAGE }}:latest

            echo "[2/3] Restart container with new image..."
            docker stop bearchive || true
            docker rm bearchive || true
            docker run -d --name bearchive \
              --env-file /home/${{ secrets.SERVER_USER }}/.env \
              -p 8080:8080 \
              ${{ env.IMAGE }}:latest
            
            echo "[3/3] Cleanup unused images..."
            docker image prune -f
